include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    unnecessary_import: true
    prefer_single_quotes: true
    avoid_empty_else: true
    cancel_subscriptions: true
    close_sinks: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_init_to_null: true
    constant_identifier_names: true
    one_member_abstracts: true
    use_key_in_widget_constructors: true
    use_build_context_synchronously: true
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
